/**
 * Autogenerated header file for rnn-2-4
 * neural network model parameters.
 * 
 * Created on: 03/10/2022 at: 10:19
 * By Michael Holmes
*/

#pragma once
#include "layers.h"

template<typename T>
class Rnn_2_4
{
public:
	const static int h = 2;
	const static int d = 1;
	const static int layers = 4;

	FccLayer<T, h, d> f;
	RnnLayer<T, h, d> l0;
	RnnLayer<T, h, h> l1;
	RnnLayer<T, h, h> l2;
	RnnLayer<T, h, h> l3;

	Rnn_2_4() {
		l0.Wih << -2.729341 ,-2.0342002;

		l0.Whh <<  0.17036283, 0.22163755,-0.6127797 ,-0.92778975;

		l0.bih << -0.2096899, 0.4739973;

		l0.bhh << -0.09538452,-0.69105047;

		l0.htn1 << 0.,0.;

		l1.Wih << -0.17657861,-1.5796613 , 1.8669199 , 5.1016483 ;

		l1.Whh <<  0.17998615,-0.8947482 , 0.16628672,-0.11702587;

		l1.bih << 0.08207554,0.39094877;

		l1.bhh << 0.00801696,0.41186023;

		l1.htn1 << 0.,0.;

		l2.Wih << -0.10098406,-0.5625597 , 1.195943  ,-0.76536983;

		l2.Whh <<  0.5601913 ,-0.1288622 ,-1.5549568 ,-0.02015822;

		l2.bih << -0.01715576, 0.47096157;

		l2.bhh <<  0.0897334 ,-0.49221122;

		l2.htn1 << 0.,0.;

		l3.Wih <<  0.06845319,-0.11383019,-0.16757894, 0.31667355;

		l3.Whh << -0.02625313, 0.49640965, 0.1726651 , 0.15925215;

		l3.bih << 0.24028167,0.39340463;

		l3.bhh <<  0.00806533,-0.13443708;

		l3.htn1 << 0.,0.;

		f.A << 0.5618275 ,0.45957944;
		f.b << -0.3761936;
	}

	void apply_model(T* x, T* y) {
		l0.apply_layer(*x);
		l1.apply_layer(l0.ht);
		l2.apply_layer(l1.ht);
		l3.apply_layer(l2.ht);
		*y=f.apply_layer(l3.ht);
	}
};